
#pragma once

/* TODO: Things we need to to impliment
   viewport
   video/media viewer (include audio) and static image

*/

namespace tyon
{
enum class e_media_source : i32
{
    none         = 0_bit,
    raster_image = 1_bit,
    vector_image = 2_bit,
    video        = 3_bit,
    render_batch = 20_bit
};

enum class e_ui_anchor : i32
{
    center        = (1 << 0),
    top_left      = (1 << 1),
    top_center    = (1 << 2),
    top_right     = (1 << 3),
    center_left   = (1 << 4),
    center_right  = (1 << 5),
    bottom_left   = (1 << 6),
    bottom_center = (1 << 7),
    bottom_right  = (1 << 8)
};

enum class e_ui_arrangement : i32
{
    horizontal_strip ,
    vertical_strip,
    diagonal_strip,
    grid,
    circle,
    spiral,
    full
};

enum class f_mouse_button : i32
{
    left   = (1 << 0),
    middle = (1 << 1),
    right  = (1 << 2),
    side1  = (1 << 3),
    side2  = (1 << 4),
};


enum class e_ui_drawable : i32
{
    none      = 0,
    any       = 1,
    image     = 2,
    vector    = 3,
    mesh      = 4,
    text      = 5
};

/** An action is a generic interface into binding events that happen to user facing input.
 *
 * A centralized system allows to making any user-interactable hook-able
 * into the many various user interaction systems that are available, user defined
 * buttons, keyboard shortcuts, pen gestures, command windows, etc.
 */
struct action
{
  // Static ID consistent across program runs
  uid id;
  fstring name;
  fstring display_name;
  fstring description;
  /** What contextual part of the program or UI the action is valid for.

    Actions can only be meaningful in specific UI contexts, so we need to store
   what context the actual belongs to, and if that context is currently
   acecssible. ie Fly Camera Controls are only valid when controlling a camera,
   but we can still bind a to different action trigger whilst in the wrong
   content- but only if the context still physically exists.

   That will be handled in external triggers but the action stores what it's supposed to be. */
  // e_action_context context;

  // Means one of the following possible triggers have been bound
  bool triggered = false;
  bool event_bound = false;
  // These triggers need to be serializable functions
  tyon::delegate<void()> trigger;
  // NOTE: Actions should not who invokes the action, they should instead link to the action.
};

struct ui_temp_action
{
    uid id;
    fstring name;
    SDL_Scancode keyscan = SDL_SCANCODE_UNKNOWN;
    bool triggered = false;
    i32 mouse_trigger_clicks = 0;
    /** This is mouse button index */
    u8 sdl_mouse_button = 0;
};

struct keybind_chain_step
{
  SDL_Scancode scancode;
  /** Not reliable way to setup keybinds, but might be useful if the user wants to remap to a named
      key with different keyboard layouts. */
  SDL_Keycode keycode;
  /// Hold down with next chain and ignore most attributes except combnie_next
  bool combine_next = false;
  /// if 0.0 is a keypress only
  f32 hold_time = 0.0;
};


struct keybind
{
    action bound_action;
    /// Describes the multi-part keybind that makes up the keybind
    array<keybind_chain_step> chain;
    /** Action is a continious hold, last key combo can be held down
        continiously and will be maintained. */
    bool held_bind = false;
};

struct gesture_chain_step
{
    v3_f32 position;
    /** Some gestures are only valid if travelling in a specified direction.
     This can be autogenerated from the gesture chain if necessary. */
    bool directional = false;
    v3_f32 direction;
};

struct gesture
{
  array<gesture_chain_step> chain;
};

struct text_drawable
{
    fstring text = "";
    transform_2d transform;
    e_ui_anchor anchor = e_ui_anchor::center;
    sdl::TTF_Font* font = nullptr;
    rgba color = rgba{.hex = 0xFFFFFF };
    rgba background_color;
    v2_f32 bounding_box;
    v2_f32 rendered_size;
    f32 size_pt = 0.0f;
    f32 size_rendered_pt = 0.0f;
    uid base_widget;

    // NOTE: These SDL surfaces are only with the SDL Render subsystem
    // SDL_Surface* surface = nullptr;
    // SDL_Texture* texture = nullptr;

    bool dirty = true;
    bool drawn_on_lcd = true;
    // LCD sub-pixel rendering can only be done if the background colour is known and uniform
    bool uniform_background_color = false;
    bool wrapped = false;
};

struct ui_interactable
{
    /* NOTE: Any important actions like event signals, hover checks will happen
     * inside the function itself. This will then bind to an 'action' which will
     * hold a user facing job.

     You can provide a context struct/pointer by using the
     generic_procedure.assign_closure() function.  Or alternatively a lambda with
     a capture, if you prefer

    [=context]() { context->member = bar; } */
    uid widget;
    generic_procedure<void()> tick;
    /** NOTE: We'll do a collision on the saved bounding box of the widget's
        geometry, then later do complex collision for accuracy.

        TODO: We can look at disabling complex collision later but I don't think it'll be needed */
};

/** Base UI component
 *
 * Widgets have an id, a parent widget, a tarnsform, and a drawable. Widgets
 * are only meant to orchestrate positioning and final draw
 * calls. Everything else is up to other code. */
struct ui_widget
{
    uid id = -1;
    fstring name;
    // Short string identifying what kind of widget this is
    // fstring type;

    uid parent = -1;
    /// What order to draw widgets in, default to drawing child widgets above parents
    /// Lower depth values are more likely to draw above other widgets
    i32 depth = 0;
    box_2d bounding_box;

    /** Transform to apply to the widget

       There's no real reason to assume UIs should be relegated to 2D space, and
       we need a depth component anyway which already *is* a third
       dimension. This also makes it easier to do fancy UI effects.
       NOTE: This used to be duplicate on the drawable this this is completely pointless honestly. */
    transform_3d transform;

    /// Where to place origin based on extents of the parent's bounding box
    e_ui_anchor anchor = e_ui_anchor::center;
    /// What part of box to treat as the origin
    e_ui_anchor origin_anchor = e_ui_anchor::center;

    /// Whether this widget particupates in all processing, transformation, collisions, etc
    bool active = true;
    /// Whether this widget participates in collision checks
    bool collisions_enabled = true;
    /// Whether or not the user can manually relocate this widget
    bool user_relocation_enabled = true;
    bool inherit_transform = true;
    bool inherit_scale = true;
    bool inherit_rotation = true;
    // TODO: move me
    /// Don't allow scales that have unmatched forward/up/right components
    bool preserve_aspect_ratio = true;

    /** Interaction Events
     * See 'interaction_data' for documentaton of these events */
    // procedure<interaction_data> on_interaction;
    // procedure<interaction_data> on_initiated_once;
    // procedure<interaction_data> on_initiated;
    // procedure<interaction_data> on_initiated_end;
    // procedure<interaction_data> on_hover;
    // procedure<interaction_data> on_hover_end;

    // -- Functions --
    /** Get list of all this widget and all its parents */
    vector<ui_widget>
    get_widget_hierarchy();

    /** Get tree of all widgets and set 'start_node' to this widget */
    n_tree<ui_widget*>
    get_tree();

    //* Combine transforms of parents all the way until the root widget */
    transform_2d
    get_root_transform();

    bool
    point_collision( v2_f32 point );

    v2_f32
    get_pin_position();
};

struct ui_layout
{
    array< entity_uid<ui_widget> > widgets;
    /** A layout many have a various number of positions to arrange widgets into.
        This specifies where in the arrangement to put it. Shared slots may be auto-arranged. */
    i32 layout_slot = 0;
    e_ui_arrangement arrangement_pattern = e_ui_arrangement::horizontal_strip;
    /// Whether or not this widget should participate in automatic placement in layouts
    bool auto_arrangement = true;
    /// Whether to use calculated spacing values or provided ones
    bool auto_spacing = true;
    /// Spacing, may be modified by a layout widget
    f32 spacing = 40.0;
    // Angle
    f32 radial_distance;
};

struct ui_font
{
    // sdl::TTF_Font* platform_font;
    f32 size_points = 0.0;
};

/** Very basic widget type only for displaying graphics on.

 NOTE: Previously I tried to give every widget a drawable but honestly it just
overloads the meaning of a widget and made the object really bloated and
unweidly to manage. This v2 iteration of the UI will split each thing into it's
own unique struct and use ui_widget as a spatial positioning tool */
struct ui_drawable
{
    uid id;
    fstring name;
    uid widget;
    bool active = true;

    e_ui_drawable type = e_ui_drawable::none;
    render_image image_;
    // vector_image vector;
    text_drawable text;
    // Base colour for untextured meshes, text, or tint
    rgba color;
    /// All drawables must be backed by a mesh unless using raw image copies.
    mesh geometry;

};

struct ui_input_state
{
    time_date_ns mouse_update_time;
    v2_f32 mouse_delta = 0;
    v2_f32 mouse_window = 0;
    /** NOTE: This has 2 axis because horizontal scroll is a thing. Particularly true of touchpads */
    v2_f32 mouse_scroll = 0;
};

/** A snapshot of data take at the start of a UI tick */
struct ui_frame
{
    ui_input_state input;
    vector<u8> scancode_states;
    vector<u8> scancode_single_press;
    f_mouse_button mouse_button_state;
    f_mouse_button mouse_button_single_press;

    v2_f32 window_size = 0;
    v2_f32 window_halfsize = 0;

    time_monotonic tooltip_hover_time = time_now();
    v2_f32 cursor;
    v2_f32 cursor_canvas;
    f32 canvas_scale;
    v2_f32 canvas_position;
    v2_f32 canvas_origin = 0;
    v2_f32 mouse_delta = 0;
    v2_f32 mouse_delta_canvas = 0;
    f32 scroll_x = 0;
    f32 scroll_y = 0;
    // if scroll has been read this frame
    bool scroll_consumed = false;
};

struct ui_context
{
    entity_uid<ui_widget> canvas;
    memory_heap_allocator permanant;
    ui_font default_font;
    // Dynamically updating window state
    ui_input_state input;
    array<ui_temp_action> actions_bound;
    std::timed_mutex actions_lock;

    ui_frame frame_prev;
    ui_frame frame;

    uid tmp_bar;
    render_image test_image;
};

extern ui_context* g_ui;

template<>
struct entity_type_definition<window>
{
    using t_entity = window;
    using t_context = entity_type_context<t_entity>;
    static constexpr cstring name = "tyon::window";
    static constexpr u128 id = uuid("965fd378-6573-4844-aa34-e6645cc3ac7a");

    PROC allocate() -> void
    {}

    PROC init( t_entity* arg ) -> fresult
    {
        return false;
    }
    PROC destroy( t_entity* arg ) -> void
    {
        auto sdl = sdl_create_platform_subsystem();
        sdl.window_close( arg );
        *arg = {};
    }

    PROC tick() -> void
    {}

    static PROC context_tick( void* context ) -> void
    {}

    static PROC destroy_all( void* context ) -> void
    {}

};

template<>
struct entity_type_definition<ui_widget>
{
    using t_entity = ui_widget;
    using t_context = entity_type_context<t_entity>;
    static constexpr cstring name = "tyon::ui_widget";
    static constexpr u128 id = uuid("a2a6cb83-8820-496b-a9e3-8ffc09c52c3f");

    PROC allocate() -> void
    {}

    PROC init( t_entity* arg ) -> fresult
    {
        return false;
    }
    PROC destroy( t_entity* arg ) -> void
    {
        *arg = {};
    }

    PROC tick( t_entity* arg ) -> void
    {}

    static PROC context_tick( void* context ) -> void
    {}

    static PROC destroy_all( void* context ) -> void
    {}

};

template<>
struct entity_type_definition<ui_drawable>
{
    using t_entity = ui_drawable;
    using t_context = entity_type_context<t_entity>;
    static constexpr cstring name = "tyon::ui_drawable";
    static constexpr u128 id = uuid( "3e73fc4a-9d81-4fae-ad5d-49d2c0d68cb7" );

    PROC allocate() -> void
    {}

    PROC init( t_entity* arg ) -> fresult
    {
        if (arg->widget.valid() == false)
        {   TYON_ERROR( "Drawable has no associated widget, did you forget to set it?" );
            return false;
        }
        ui_widget* widget = entity_allocate<ui_widget>();
        // widget
        entity_init( widget );
        mesh_init( &arg->geometry );

        return false;
    }
    PROC destroy( t_entity* arg ) -> void
    {
        *arg = t_entity{};
    }

    PROC tick( t_entity* arg ) -> void
    {
        if (arg->active == false)
        {   return; }

        // SECTION: Regenerate appropriate variables
        ui_widget* widget = entity_search<ui_widget>( arg->widget ).copy_default(nullptr);
        if (widget == nullptr)
        {   TYON_ERROR( "Failed to find base widget associated with drawable widget" );
        }
        // TODO: Cache this result for high poly geometry
        switch (arg->type)
        {
            case e_ui_drawable::mesh:
            {
                widget->bounding_box = mesh_bounding_box_2d( &arg->geometry );

                // TODO: Construct transform from widget hierarchy
                arg->geometry.transform = widget->transform;

                // Queue the drawable for drawing
                g_render->draw_queue_mesh.push_tail( &arg->geometry );
            }
            case e_ui_drawable::text:
            {

            }
            default: break;
        }
    }

    static PROC context_tick( void* context ) -> void {}
    static PROC destroy_all( void* context ) -> void {}

};

using widget_tree = n_tree<ui_widget*>;

PROC ui_init() -> fresult;
PROC ui_tick() -> void;
PROC ui_destroy() -> void;
PROC ui_destroy() -> void;

/** NOTE: The tick  is broken into frame_start and frame_end  because there is a
 lot of  boilerplate that goes  at the start  and end of  the tick that  is very
 boilerplatey and doesn't need  to be looked at much, but  is very important and
 order  dependant  and  mustn't  be   confused  with  other  code.  Like  memory
 management, defragmentation,  and clearing old  state, getting events  from the
 OS- etc. */

PROC ui_tick_start() -> void;
PROC ui_tick_end() -> void;

/** Does a collision to test if a point falls inside a bounding box.

 NOTE: That box size uses center origin box coordinates*/
PROC ui_point_box_collision( v2_f32 point, v2_f32 box_pos, v2_f32 box_size ) -> bool;

PROC ui_widget_construct_tree() -> widget_tree;

/** Creates a new action

    Takes ui_temp_action as arguments, initializes the id and returns the uid also
    NOTE: Thread safe.
    NOTE: May fail if mutex is busy. Waits up to 1ms */
PROC ui_action_create( ui_temp_action* arg ) -> uid;

/** Returns true if the supplied action has been triggered since last creation

 NOTE: Thread safe.
 NOTE: May return false if a mutex is busy*/
PROC ui_action_triggered( uid action ) -> fresult;

}
